version: "3"
services:
  api-gate-way:
    build:
      context: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.dev.env
    environment:
      - PORT=4000
