module.exports={
    MONGO_IP:process.env.MONGO_IP || "mongo",
    MONGO_PORT:process.env.MONGO_PORT || 27017,
    MONGO_USER:process.env.MONGO_USER,
    MONGO_PASSWORD:process.env.MONGO_PASSWORD,
    USER_DB_NAME:process.env.USER_DB_NAME,
    POSTS_DB_NAME:process.env.POSTS_DB_NAME,
    SESSION_ABSOLUTE_TIMEOUT:process.env.SESSION_ABSOLUTE_TIMEOUT || 1000*60,
    GOOGLE_OAUTH2_CLIENT_ID:process.env.GOOGLE_OAUTH2_CLIENT_ID,
    GOOGLE_OAUTH2_CLIENT_SECRET:process.env.GOOGLE_OAUTH2_CLIENT_SECRET,
    GOOGLE_OAUTH2_CLIENT_REDIRECT_URI:process.env.GOOGLE_OAUTH2_CLIENT_REDIRECT_URI,
} 
